name: 'Build raeda'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - main
permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Environment variables for Terraform version and working directory
    env:
      TF_VERSION: v1.9.6  # Specify the Terraform version here
#      TF_WORKING_DIR: ./terraform  # Directory where your Terraform files are stored

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Create tfvars file
      run: |
        mkdir ~/.kube
        echo '${{ secrets.KUBE_CONFIG }}' >> ~/.kube/config
        echo '${{ secrets.TF_TERRAFORM_VARS }}' >> terraform.tfvars

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
#      working-directory: ${{ env.TF_WORKING_DIR }}
      env:
        TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      run: make dev